-- Replace 'YourSchemaName' with 'Silver' or 'Gold'
USE My_Hospital
SELECT 
    t.TABLE_SCHEMA,
    t.TABLE_NAME,
    c.COLUMN_NAME,
    c.DATA_TYPE + 
        ISNULL('(' + 
               CASE 
                   WHEN c.DATA_TYPE IN ('varchar', 'nvarchar', 'char', 'nchar') THEN 
                       CASE WHEN c.CHARACTER_MAXIMUM_LENGTH = -1 THEN 'MAX' ELSE CAST(c.CHARACTER_MAXIMUM_LENGTH AS VARCHAR) END
                   WHEN c.DATA_TYPE IN ('decimal', 'numeric') THEN 
                       CAST(c.NUMERIC_PRECISION AS VARCHAR) + ',' + CAST(c.NUMERIC_SCALE AS VARCHAR)
                   ELSE NULL
               END + ')', '') AS DATA_TYPE,
    CASE WHEN pk.COLUMN_NAME IS NOT NULL THEN 'YES' ELSE 'NO' END AS IS_PRIMARY_KEY,
    fk.CONSTRAINT_NAME AS FOREIGN_KEY_NAME,
    fk.REFERENCED_TABLE_NAME,
    fk.REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLES t
JOIN INFORMATION_SCHEMA.COLUMNS c
    ON t.TABLE_NAME = c.TABLE_NAME AND t.TABLE_SCHEMA = c.TABLE_SCHEMA
LEFT JOIN (
    SELECT ku.TABLE_SCHEMA, ku.TABLE_NAME, ku.COLUMN_NAME
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE ku
        ON tc.CONSTRAINT_NAME = ku.CONSTRAINT_NAME
    WHERE tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
) pk
    ON c.TABLE_SCHEMA = pk.TABLE_SCHEMA 
   AND c.TABLE_NAME = pk.TABLE_NAME 
   AND c.COLUMN_NAME = pk.COLUMN_NAME
LEFT JOIN (
    SELECT 
        fk.TABLE_SCHEMA,
        fk.TABLE_NAME,
        fkc.COLUMN_NAME,
        fk.CONSTRAINT_NAME,
        pk.TABLE_NAME AS REFERENCED_TABLE_NAME,
        pkc.COLUMN_NAME AS REFERENCED_COLUMN_NAME
    FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
    JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS fk
        ON rc.CONSTRAINT_NAME = fk.CONSTRAINT_NAME
    JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS pk
        ON rc.UNIQUE_CONSTRAINT_NAME = pk.CONSTRAINT_NAME
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE fkc
        ON fk.CONSTRAINT_NAME = fkc.CONSTRAINT_NAME
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE pkc
        ON pk.CONSTRAINT_NAME = pkc.CONSTRAINT_NAME 
           AND fkc.ORDINAL_POSITION = pkc.ORDINAL_POSITION
) fk
    ON c.TABLE_SCHEMA = fk.TABLE_SCHEMA 
   AND c.TABLE_NAME = fk.TABLE_NAME 
   AND c.COLUMN_NAME = fk.COLUMN_NAME
WHERE  t.TABLE_SCHEMA in ( 'gold','silver') AND T.TABLE_NAME LIKE '%test%'
ORDER BY t.TABLE_NAME, c.ORDINAL_POSITION;

